Repository devosoft/Empirical, pull requests merged in 2018-03, with the labels that each got.

#145 Othello.h bug fix
  source/games/Othello.h
Labels: Goal: Bug Fix, Merge: Ready!!

#135 The attribute packs library
  examples/tools/Makefile
  examples/tools/attrs.cc
  source/meta/type_traits.h
  source/tools/attrs.h
  tests/test_meta.cc
  tests/test_tools.cc
Labels: Merge: Ready!!

#150 Add GetStepButton to Animate.h
  source/Evolve/World_iterator.h
  source/web/Animate.h
Labels: Topic: Web Interface

#153 A Feature and a Fix for DataFile.h
  source/data/DataFile.h
  tests/data/test_file.dat
Labels: Topic: Data tools

#152 Removes + operator from attrs.h
  examples/tools/attrs.cc
  source/tools/attrs.h
  tests/test_tools.cc
Labels: Merge: Ready!!

#154 Make PrintHeaderKeys optional in DataFile builders
  source/Evolve/World.h
Labels: Topic: Data tools, Topic: Evolution Framework

#156 Line edits
  Planning/DEVEL_NOTES
  Planning/Geometry
  Planning/Phenotypes
  Planning/Signals
  README.md
  doc/dev/getting-started.rst
  doc/dev/guide-to-testing.rst
  doc/dev/index.rst
Labels: Merge: Ready!!
