Repository devosoft/Empirical, pull requests merged in 2018-02, with the labels that each got.

#142 Tests no longer define TDEBUG (and undefine NDEBUG)
  .gitignore
  source/tools/set_utils.h
  source/tools/stats.h
  source/tools/vector_utils.h
  tests/Makefile
  tests/test_assert.cc
  tests/test_base.cc
  tests/test_constexpr.cc
  tests/test_data.cc
  tests/test_evo.cc
  tests/test_meta.cc
  tests/test_tools.cc
Labels: Merge: Ready!!, Topic: Testing

#141 Othello game implementation
  examples/games/Othello.cc
  source/games/Othello.h
  source/hardware/AvidaGP.h
  source/hardware/EventDrivenGP.h
  tests/Makefile
  tests/test_games.cc
Labels: Merge: Ready!!

#140 Fixed documentation + added more
  doc/_build/.gitignore
  doc/build/.gitignore
  doc/conf.py
  doc/dev/getting-started.rst
  doc/dev/index.rst
  doc/index.rst
  doc/library/base/base.rst
  doc/library/d3.rst
  doc/library/data/data.rst
  doc/library/index.rst
  doc/library/tools/tools.rst
  doc/library/web/d3/d3-contents.rst
  doc/library/web/d3/d3-intro.rst
  doc/library/web/d3/d3.rst
  doc/library/web/web.rst
  source/base/assert.h
Labels: Merge: Ready!!, Topic: Documentation
