Repository devosoft/Empirical, pull requests merged in 2018-06, with the labels that each got.

#168 Fixed docs; updated tests to include multiple compilers and debug modes
  .travis.yml
  Makefile
  README.md
  doc/make_docs.sh
  source/Evolve/World_select.h
  source/tools/BitVector.h
  tests/Makefile
  tests/test_assert.cc
  tests/test_base.cc
  tests/test_constexpr.cc
  tests/test_data.cc
  tests/test_evo.cc
  tests/test_geometry.cc
  tests/test_tools.cc
  third-party/requirements.txt
Labels: Merge: Ready!!, Topic: Documentation, Topic: Testing

#178 SignalGP Update + SignalGP Utilities
  examples/hardware/Makefile
  examples/hardware/SignalGP.cc
  source/hardware/EventDrivenGP.h
  source/hardware/signalgp_utils.h
  tests/Makefile
  tests/test_hardware.cc
Labels: Goal: Enhancement

#182 Fix excessive memory usage caused by default behavior of DataFiles with emscripten
  .bumpversion.cfg
  source/base/array.h
  source/base/assert.h
  source/base/errors.h
  source/data/DataFile.h
  source/data/DataInterface.h
  source/data/DataManager.h
  source/data/DataNode.h
  source/tools/NullStream.h
  tests/test_tools.cc
Labels: Merge: Ready!!, Topic: Core Tools, Topic: Data tools

#176 New emp::Surface is working; OpenWorld has organisms backed by random code.
  apps/OpenWorld/source/OpenOrg.h
  apps/OpenWorld/source/OpenWorld.h
  apps/OpenWorld/source/config.h
  apps/OpenWorld/source/native/OpenWorld.cc
  apps/OpenWorld/source/web/OpenWorld-web.cc
  examples/Makefile
  examples/geometry/Makefile
  examples/geometry/Surface.cc
  source/Evolve/World.h
  source/config/config.h
  source/geometry/Angle2D.h
  source/geometry/Body2D.h
  source/geometry/Surface.h
  source/web/canvas_utils.h
Labels: Merge: Ready!!
