Repository devosoft/Empirical, pull requests merged in 2020-03, with the labels that each got.

#242 Improve ArgManager to accept flag aliases separated by '|'
  source/config/ArgManager.h
  tests/test_config.cc
Labels: Goal: Enhancement, Merge: Ready!!

#272 Put no-Emscripten macro guards on crypto, ssl
  source/tools/matchbin_metrics.h
Labels: Goal: Bug Fix, Merge: Ready!!

#274 fix for #247
  source/base/array.h
  tests/test_base.cc
Labels: Merge: Ready!!
