Repository devosoft/Empirical, pull requests merged in 2020-07, with the labels that each got.

#321 Update web testing to use Karma/Mocha testing framework
  source/web/_MochaTestRunner.h
  source/web/library_emp.js
  tests/Makefile
  tests/web/Element.cc
  tests/web/GetUrlParams.cc
  tests/web/JSWrap.cc
  tests/web/JSWrap.html
  tests/web/Makefile
  tests/web/TestRunner.html
  tests/web/Widget.cc
  tests/web/color_map.cc
  tests/web/js_utils.cc
  tests/web/karma.conf.js
  tests/web/run_tests.sh
  tests/web/test_header.js
  tests/web/test_widget.cc
  tests/web/test_widget.html
  tests/web/visualizations.cc
Labels: Goal: Enhancement, Merge: Ready!!, Prereq: Emscripten Programmer, Prereq: JavaScript Programmer, Topic: Emscripten Tools, Topic: Testing

#331 Add Dockerfile
  Dockerfile
  README.md
Labels: Goal: Enhancement, Merge: Ready!!

#327 Added pass_map_to_javascript util in js_utils.h
  source/web/js_utils.h
  tests/web/js_utils.cc
Labels: Goal: Enhancement, Merge: Ready!!, Prereq: Emscripten Programmer, Prereq: JavaScript Programmer, Topic: Emscripten Tools

#344 Magical codecov fix: coverage-* -> cov-*
  tests/Evolve/Makefile
  tests/base/Makefile
  tests/config/Makefile
  tests/constexpr/Makefile
  tests/data/Makefile
  tests/games/Makefile
  tests/geometry/Makefile
  tests/hardware/Makefile
  tests/meta/Makefile
  tests/scholar/Makefile
  tests/tools/Makefile
Labels: Merge: Ready!!
