Repository devosoft/Empirical, pull requests merged in 2020-02, with the labels that each got.

#265 Very confusing and mysterious static mess
  source/tools/matchbin_metrics.h
  tests/test_tools.cc
Labels: Goal: Bug Fix, Goal: Recruit Help!, Merge: Ready!!

#269 Make check for synchronous world more robust
  source/Evolve/World.h
Labels: Merge: Ready!!

#271 Add cryptographic hash metric
  source/tools/BitSet.h
  source/tools/matchbin_metrics.h
  tests/test_tools.cc
Labels: Goal: Enhancement, Merge: Ready!!

#273 Nix spawn core in SignalGP constructor
  examples/hardware/SignalGP.cc
  source/hardware/EventDrivenGP.h
  tests/test_hardware.cc
Labels: Goal: Enhancement, Merge: Ready!!
